services:
  web:
    build: .
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      - LOG_LEVEL=INFO
      - MY_VAR=SOME_SECRET_STRING
    volumes:
      - .:/app
    restart: unless-stopped
